title: David Dolejsi
baseURL: https://gethugothemes.com/academia/site/
copyright: Copyright &copy; 2025
googleAnalytics: '#####'
theme: academia-hugo
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
enableEmoji: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
services:
  disqus:
    Shortname: themefisher-template
build:
  buildStats:
    enable: yes
  cachebusters:
    - source: assets/.*\.(js|ts|jsx|tsx)
      target: (js|scripts|javascript)
    - source: assets/.*\.(css|sass|scss)$
      target: (css|styles|scss|sass)
    - source: assets/.*\.(.*)$
      target: $1
  noJSConfigInAssets: no
  useResourceCacheWhen: fallback
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
blackfriday:
  angledQuotes: no
  extensions: backslashLineBreak
  hrefTargetBlank: yes
  latexDashes: yes
imaging:
  anchor: smart
  quality: 90
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: yes
caches:
  assets:
    dir: :resourceDir/_gen
    maxAge: 720h
  images:
    dir: :resourceDir/_gen
    maxAge: 720h
pagination:
  pagerSize: 10
